import { jsPDF } from 'jspdf'
import { format } from 'date-fns'

export interface ScanReportData {
  scanId: string
  domain: string
  scanDate: string
  securityScore: number
  totalFindings: number
  findings: {
    critical: number
    high: number
    medium: number
    low: number
  }
  scanFindings: Array<{
    title: string
    severity: string
    description: string
    affected_url: string
    recommendation: string
    owasp_category?: string
  }>
}

/**
 * Generate PDF security report
 */
export function generatePDFReport(data: ScanReportData): jsPDF {
  const doc = new jsPDF()
  let yPosition = 20

  // Header
  doc.setFontSize(20)
  doc.setTextColor(0, 0, 0)
  doc.text('Security Scan Report', 20, yPosition)
  yPosition += 10

  doc.setFontSize(12)
  doc.setTextColor(100, 100, 100)
  doc.text(`Domain: ${data.domain}`, 20, yPosition)
  yPosition += 6
  doc.text(`Scan Date: ${format(new Date(data.scanDate), 'PPpp')}`, 20, yPosition)
  yPosition += 6
  doc.text(`Scan ID: ${data.scanId}`, 20, yPosition)
  yPosition += 15

  // Security Score
  doc.setFontSize(16)
  doc.setTextColor(0, 0, 0)
  doc.text('Security Score', 20, yPosition)
  yPosition += 10

  const scoreColor = data.securityScore >= 80 ? [0, 150, 0] : data.securityScore >= 60 ? [255, 165, 0] : [255, 0, 0]
  doc.setFontSize(32)
  doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2])
  doc.text(`${data.securityScore}/100`, 20, yPosition)
  yPosition += 15

  // Summary
  doc.setFontSize(16)
  doc.setTextColor(0, 0, 0)
  doc.text('Summary', 20, yPosition)
  yPosition += 10

  doc.setFontSize(12)
  doc.setTextColor(0, 0, 0)
  doc.text(`Total Findings: ${data.totalFindings}`, 20, yPosition)
  yPosition += 6
  doc.setTextColor(200, 0, 0)
  doc.text(`Critical: ${data.findings.critical}`, 20, yPosition)
  yPosition += 6
  doc.setTextColor(255, 100, 0)
  doc.text(`High: ${data.findings.high}`, 20, yPosition)
  yPosition += 6
  doc.setTextColor(255, 200, 0)
  doc.text(`Medium: ${data.findings.medium}`, 20, yPosition)
  yPosition += 6
  doc.setTextColor(100, 100, 100)
  doc.text(`Low: ${data.findings.low}`, 20, yPosition)
  yPosition += 15

  // Findings
  if (data.scanFindings.length > 0) {
    doc.setFontSize(16)
    doc.setTextColor(0, 0, 0)
    doc.text('Detailed Findings', 20, yPosition)
    yPosition += 10

    for (let i = 0; i < data.scanFindings.length; i++) {
      const finding = data.scanFindings[i]

      // Check if we need a new page
      if (yPosition > 250) {
        doc.addPage()
        yPosition = 20
      }

      // Severity color
      const severityColors: Record<string, [number, number, number]> = {
        critical: [200, 0, 0],
        high: [255, 100, 0],
        medium: [255, 200, 0],
        low: [100, 100, 100],
      }
      const color = severityColors[finding.severity] || [0, 0, 0]

      doc.setFontSize(12)
      doc.setTextColor(color[0], color[1], color[2])
      doc.setFont(undefined, 'bold')
      doc.text(`${i + 1}. ${finding.title} [${finding.severity.toUpperCase()}]`, 20, yPosition)
      yPosition += 7

      doc.setFontSize(10)
      doc.setTextColor(0, 0, 0)
      doc.setFont(undefined, 'normal')
      
      // Description
      const descLines = doc.splitTextToSize(finding.description, 170)
      doc.text(descLines, 20, yPosition)
      yPosition += descLines.length * 5 + 3

      // Affected URL
      doc.setFont(undefined, 'italic')
      doc.text(`URL: ${finding.affected_url}`, 20, yPosition)
      yPosition += 5

      // Recommendation
      doc.setFont(undefined, 'normal')
      doc.text('Recommendation:', 20, yPosition)
      yPosition += 5
      const recLines = doc.splitTextToSize(finding.recommendation, 170)
      doc.text(recLines, 20, yPosition)
      yPosition += recLines.length * 5 + 5

      // OWASP Category
      if (finding.owasp_category) {
        doc.setFontSize(9)
        doc.setTextColor(100, 100, 100)
        doc.text(`OWASP: ${finding.owasp_category}`, 20, yPosition)
        yPosition += 5
      }

      yPosition += 5
    }
  }

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(
      `Page ${i} of ${pageCount} - Generated by Security Scanner SaaS`,
      105,
      290,
      { align: 'center' }
    )
  }

  return doc
}
