/**
 * PDF Report Generation
 * Erstellt detaillierte Security Reports als PDF
 */

import jsPDF from 'jspdf'

export interface ReportData {
  scanId: string
  domain: string
  scanDate: string
  securityScore: number
  totalFindings: number
  findings: Array<{
    severity: 'low' | 'medium' | 'high' | 'critical'
    title: string
    description: string
    affected_url?: string
    remediation: string
    owasp_category?: string
  }>
}

export function generatePDFReport(data: ReportData): Blob {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  let yPos = 20

  // Header
  doc.setFontSize(20)
  doc.text('Security Scan Report', pageWidth / 2, yPos, { align: 'center' })
  yPos += 10

  doc.setFontSize(12)
  doc.text(`Domain: ${data.domain}`, 20, yPos)
  yPos += 7
  doc.text(`Scan Date: ${data.scanDate}`, 20, yPos)
  yPos += 7
  doc.text(`Scan ID: ${data.scanId}`, 20, yPos)
  yPos += 10

  // Security Score
  doc.setFontSize(16)
  doc.text(`Security Score: ${data.securityScore}/100`, 20, yPos)
  yPos += 10

  // Summary
  doc.setFontSize(12)
  doc.text(`Total Findings: ${data.totalFindings}`, 20, yPos)
  yPos += 15

  // Findings
  doc.setFontSize(14)
  doc.text('Findings:', 20, yPos)
  yPos += 10

  doc.setFontSize(10)
  for (const finding of data.findings) {
    // Prüfe ob neue Seite nötig
    if (yPos > pageHeight - 40) {
      doc.addPage()
      yPos = 20
    }

    // Severity Color
    const severityColors: Record<string, [number, number, number]> = {
      critical: [220, 53, 69],
      high: [255, 193, 7],
      medium: [255, 152, 0],
      low: [40, 167, 69],
    }

    const color = severityColors[finding.severity] || [0, 0, 0]
    doc.setTextColor(color[0], color[1], color[2])
    doc.setFont(undefined, 'bold')
    doc.text(`${finding.severity.toUpperCase()}: ${finding.title}`, 20, yPos)
    yPos += 7

    doc.setTextColor(0, 0, 0)
    doc.setFont(undefined, 'normal')
    doc.text(`Description: ${finding.description}`, 25, yPos, {
      maxWidth: pageWidth - 45,
    })
    yPos += 7

    if (finding.affected_url) {
      doc.text(`Affected URL: ${finding.affected_url}`, 25, yPos)
      yPos += 7
    }

    if (finding.owasp_category) {
      doc.text(`OWASP: ${finding.owasp_category}`, 25, yPos)
      yPos += 7
    }

    doc.text(`Remediation: ${finding.remediation}`, 25, yPos, {
      maxWidth: pageWidth - 45,
    })
    yPos += 10
  }

  // Footer
  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.text(
      `Page ${i} of ${totalPages} - Generated by Security Scanner SaaS`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    )
  }

  return doc.output('blob')
}
